# Generated by Django 5.2.17 on 2026-09-28 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='类别名称')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='明细')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实付款')),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='发票金额')),
                ('invoice_no', models.CharField(blank=True, max_length=50, verbose_name='发票号码')),
                ('order_no', models.CharField(max_length=64, verbose_name='支付订单号')),
                ('invoice_file', models.FileField(upload_to='invoices/%Y%m/', verbose_name='票据')),
                ('payment_screenshot', models.ImageField(upload_to='payments/%Y%m/', verbose_name='支付截图')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已退回')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.category', verbose_name='类别')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='付款人')),
            ],
            options={
                'verbose_name': '报销条目',
                'verbose_name_plural': '报销条目',
                'ordering': ['-created_at'],
            },
        ),
    ]
