# Generated by Django 5.2.17 on 2026-09-28 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_pk', models.PositiveIntegerField(verbose_name='条目编号')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('delete', '删除')], max_length=10, verbose_name='动作')),
                ('actor_name', models.CharField(blank=True, max_length=100, verbose_name='操作人姓名')),
                ('snapshot', models.JSONField(default=dict, verbose_name='变更明细')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.item', verbose_name='条目')),
            ],
            options={
                'verbose_name': '操作留痕',
                'verbose_name_plural': '操作留痕',
                'ordering': ['-created_at'],
            },
        ),
    ]
