# Generated by Django 6.1.1 on 2026-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_batch_item_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='archived',
            field=models.BooleanField(default=False, help_text='存档批次只读：条目与附件不可增改删', verbose_name='已存档'),
        ),
    ]
