# Generated by Django 6.1.1 on 2026-10-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_batch_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('invoice', '发票'), ('payment', '支付记录'), ('refund', '退款记录'), ('support', '证明材料')], max_length=10, verbose_name='类型'),
        ),
    ]
