# Generated by Django 6.1.1 on 2026-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_office_supplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='comment',
            field=models.CharField(blank=True, max_length=200, verbose_name='审核批语'),
        ),
    ]
